openapi: 3.0.0
info:
  title: Shield Pay API
  version: 1.0.0

servers:
  - url: https://{host}
    description: Sandbox environments
    variables:
      host:
        enum:
          - gateway-sandbox.shieldpay.org
          - auth-sandbox.shieldpay.org
        default: gateway-sandbox.shieldpay.org

  - url: http://{host}
    description: Local development
    variables:
      host:
        enum:
          - localhost:5000
          - localhost:9000
        default: localhost:5000

paths:
  /api/oauth/merchant/token:
    post:
      tags:
        - Authentication
      summary: Obtain Merchant Access Token
      description: Securely verifies merchant credentials and returns an access token, please use auth-sandbox.shieldpay.org for sandbox.
      parameters:
        - name: X-Signature
          in: header
          required: true
          schema:
            type: string
            description: RSA-SHA256 signature (Base64-encoded) of the original unencrypted payload
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            example: application/json
            description: Must be application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: string
                  description: |
                    Encrypted RSA payload containing:
                    - `clientId`
                    - `clientSecret`
                    - `registeredClient`
                  example: hAzlCRRA8N65AR6LOF3N...
      responses:
        '200':
          description: Access token response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      accessTokenExpiresAt:
                        type: integer
                        description: Token expiry duration in seconds
                      accessToken:
                        type: string
                        description: JWT access token
                      tokenType:
                        type: string
                        description: Token type (e.g. Bearer)
                      durationIn:
                        type: string
                        description: Duration unit (e.g. Seconds)
                  message:
                    type: string
                    example: success
        '400':
          description: Invalid signature or encrypted data
          content:
            application/json:
              examples:
                InvalidSignature:
                  summary: Invalid Signature
                  value:
                    code: 400
                    data: invalid signature
                    message: error
                InvalidData:
                  summary: Invalid Data
                  value:
                    code: 400
                    data: invalid encrypted data
                    message: error


  /api/v1/payment/intent:
    post:
      tags:
        - Payment API
      summary: Create Payment Intent
      description: Create a payment intent with order and user details.
      parameters:
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            example: application/json
        - name: Accept
          in: header
          required: true
          schema:
            type: string
            example: application/json
        - name: X-Request-Id
          in: header
          required: true
          schema:
            type: string
            example: 01HZY3X9WD27Z3X0BPX3CTH1QN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                referenceId:
                  type: string
                amount:
                  type: string
                currencyCode:
                  type: string
                countryCode:
                  type: string
                languageCode:
                  type: string
                callbackUrl:
                  type: string
                webhookUrl:
                  type: string
                expiryDate:
                  type: string
                userFirstName:
                  type: string
                userLastName:
                  type: string
                userEmail:
                  type: string
                userMobile:
                  type: string
                ipAddress:
                  type: string
                transactionMode:
                  type: string
                address:
                  type: string
                city:
                  type: string
                paymentOptionCode:
                  type: string
                intentType:
                  type: string
                orderDescription:
                  type: string
                allowedPaymentNetworks:
                  type: array
                  items:
                    type: string
                metadata:
                  type: object
                  additionalProperties: true
                orderDetails:
                  type: array
                  items:
                    type: object
                    properties:
                      itemDescription:
                        type: string
                      price:
                        type: number
                      itemName:
                        type: string
                      quantity:
                        type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }

  /api/v1/payment/inquiry/request/{requestId}:
    get:
      tags:
        - Payment API
      summary: Payment Inquiry Request (BY Request ID)
      description: Retrieve payment details using the request ID.
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            example: application/json
        - name: Accept
          in: header
          required: true
          schema:
            type: string
            example: application/json
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: Bearer XXXXXXX
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }

  /api/v1/payment/inquiry/{paymentId}:
    get:
      tags:
        - Payment API
      summary: Payment Inquiry Request (BY Payment ID)
      description: Retrieve payment details using the payment ID.
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            example: application/json
        - name: Accept
          in: header
          required: true
          schema:
            type: string
            example: application/json
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: Bearer XXXXXXX
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }

  /api/v1/payment/refund/request/{requestId}:
    post:
      tags:
        - Payment API
      summary: Payment Refund Request (BY Request ID)
      description: Submit a refund request for a specific payment by request ID.
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            example: application/json
        - name: Accept
          in: header
          required: true
          schema:
            type: string
            example: application/json
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: Bearer XXXXXXX
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                reason:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
